export const EMAIL_CHANGED = 'EMAIL_CHANGED';

export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGIN_USER = 'LOGIN_USER';

export const LOGIN_AUTHENTICATED = 'LOGIN_AUTHENTICATED';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const USER_PROFILE = 'USER_PROFILE';

export const QUESTIONS = 'QUESTIONS'

export const DEFAULT_QUESTION = 'DEFAULT_QUESTION';

export const CUSTOM_QUESTIONS = 'CUSTOM_QUESTIONS';

export const PATIENT_DETAILS = 'PATIENT_DETAILS';

export const PATIENT_DATA = 'PATIENT_DATA';

export const PATIENT_DATA_FAIL = 'PATIENT_DATA_FAIL';

export const PATIENT_PROVIDER_INFO = 'PATIENT_PROVIDER_INFO';

export const SURVEY_QUESTIONS = 'SURVEY_QUESTIONS';

export const SURVEY_PATIENT_DETAILS = 'SURVEY_PATIENT_DETAILS';

export const ACTIVE_SURVEYS = 'ACTIVE SURVEYS';

export const SUBMIT_QUESTIONNAIRES = 'SUBMIT_QUESTIONNAIRES';
export const REPORT_PATIENT_DATA = 'REPORT_PATIENT_DATA';


export const ERROR_SUBMIT_QUESTIONNAIRES = 'ERROR_SUBMIT_QUESTIONNAIRES';


